# Set folder to clover (must be the same on travis)
coverage_clover: build/logs/clover.xml
# Same folder here
json_path: build/logs/coveralls-upload.json
# Don't touch that
service_name: travis-ci
repo_token: 75tmuvJZ1IX8S5cop8xWVVI9WYyTSKqOq
