language: php
# Allows use container-based infrastructure
sudo: false
# Start docker  service
services:
 - docker
# Cache composer packages so "composer install" is faster

# Matrix to test in every php version
matrix:
 # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
 fast_finish: true
 include:
   - php: 7.0
   - php: 7.2
 allow_failures:
   - php: hhvm
install:
 - composer install
 - cp app/config/parameters.yml.dist app/config/parameters.yml
 - php bin/console doctrine:database:create --env=test
 - php bin/console doctrine:schema:create --env=test
 - php bin/console doctrine:fixtures:load -n --env=test

#before script installation
before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
# Run script
script:
 - find . -name '*.php' -exec php -l {} \;
# After a build, send email notification with the build results
