language: php
sudo: false
services:
- docker
matrix:
  fast_finish: true
  include:
  - php: 7.0
  - php: 7.2
  allow_failures:
  - php: 7.2
before_script:
- curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
jobs:
  include:
  - stage: Static Code Analysis
    script:
    - find . -name '*.php' -exec php -l {} \;
  - stage: Unit Testing
    script:
    - phpunit --coverage-html ./index.html /tests
  - stage: Docker Image Building
    script:
      - docker build --tag $DOCKER_USER/Road-mapping .
  - stage: Security Check
    script:
      - curl -s https://ci-tools.anchore.io/inline_scan-latest | bash -s -- $DOCKER_USER/Road-mapping
  - stage: Docker Image Registry
    script:
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin 
      - docker push $DOCKER_USER/Road-mapping
  - stage: deploy
    script:
      - echo "Deploying the container to beanstalk"


global:
  - secure: WujBjVUelfDjzMe2A1lSNggjwIYzOEe96OCqa0ZfYdMvuN2beej2KgQbWysl4p7WFUA9eOq/nB8ChPaPZKY6Lly6t5B39j1fnN+5xsApDtGGMNhtQIrQrmjFPfRJkkVxqzFPhvaU9SRvxIb2CjmGQ6MlCOTIqigbkL7/cYLNyysTquuI6r8dpG8yHQoWMXDNItsWtGjOTmZG3uHLAeCWK6sknAfG9iGfgeJA20bvbDvi9diMInCKGqQogyWWBJdtwQDYridKzNDcH/+Bx9xE+qjVWd7g3OiIt9H5ocSLMckxW7gL5kgNTZGhNPizNvCk4+NHnQqqlEYNk7CsDhxfFlXTEcG3VAZIYvm10U8O+wVYvBYI7txATbTWnHVFBP3fPmRgurwauH/HEVKGkx6e9H9s5RvKOcYqH/4dI0q5knVwmIEZ7eZToE281qvlFc3Y+aXeU2AfNvGgRdIIi5Sq95ZRUUOltmYykrj+LYXpZ8b7rxfrTtVTkLKY/lslFuEj9TPQ/DSEsYZekw5nUl4wxZ++9mUvK4+zADDb5DUit94zMwAbS/G+nmA0zPFLzxDPXk8mU7AzxDZtkC9bZMqZxwq3SHHwPa2UBRc6dv760rv9+yW6T/L7S0ZmmGUef3axU1ZCMLK+WDgIXQvumKXJd91TaUz3wx3WWOYq/pvB6cY=
  - secure: H51cEI9Wn06TpyeqDeMrj+AcS0oHp8h5t82rwCMROfp2kYc5zz1BedmBK293cHwfnv6mN5uAYSzPHZOBkeUY/zFWjytebYE2aPPHoC1J+WAKXmW3+2eny7AUlNWSSiUuWZ67yJafP0ffviacYCePpZPyTC/8zOnnyRO+WPOEmDtkZEea537x+ELHqzVZfQbwpMGFGNk/hAv7e6l+eF5e/aktXWwNfiObYmV7wvDEjAsIf1IIj1/KKk+x14QZ0YRWzWXpKr1a4u4aWvRcVoZblYHYnWm3TL1MxHQd9Clp17JWcQ6ulW28Esza1cCTpCn6jWpzFDyZXP8wogTNxBc8r55UvLSqmGvOTFR1fTerqCcjMafefsWTIcqyZAUUnPuVgBJrEXgFhFUKmR0IU1Eme2G/OdTn0YP4Xif7eCC4fTYRprx6P5MlipnCmL62XnCfphKXMkwGPHS74O4slgOZA0EheJiIZdPSp0rCMtkq5aXW5mRGSBpZwZ8hYpyHekhQcLX5jrhKlnaISayANOKcx5DK/TVyGGxobrv3lOWsPii6J1pjzGFT6/j5jXM2OHE6d0Bc2/IO/KzMK4dK9M6wJFKhW5uSIHnZxs+LG2CgkfIfzkfd1nyGGwUTl88sVaY+JHRlUPvRlWHEezzqtEJK317U5gr5/PLyo0uXSNyzriY=
