language: php
sudo: false
services:
- docker
php:
- '7.3'
cache:
  directories:
  - "$HOME/.composer/cache"
before_script:
- curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
jobs:
  include:
  - stage: Static Code Analysis
    script:
    - find . -name '*.php' -exec php -l {} \;
  - stage: Docker Image Building
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build -t $DOCKER_USERNAME/road-mapping .
    - docker push $DOCKER_USERNAME/road-mapping
  - stage: Security Check
    script:
    - curl -s https://ci-tools.anchore.io/inline_scan-latest | bash -s -- -f -d Dockerfile $DOCKER_USERNAME/road-mapping:latest
  - stage: deploy
    script:
    - echo "Deploying the container to beanstalk"
env:
  global:
  - secure: Li/2XLCAzI/FRF8bvNKPk++Su4M6X2kSwK/rf4/7PV90yFQ1hfiNqRhUMZpMNd1ArSFlgey99RRtnE+HuJBVQoN2I+Z5tBrlhRPCySh4Fzp0QnCZpJ97F5pv3PEr/5mOb+9Bf3YrUq4XEPDhNSYzGIHPHXp2uGCEwV71L7lT7E/+jhmS9TmVnsTncYME2am+coJU6j7BjwjBXuwFZDV91Jw06VcSf+hMYv6SoXnRGesIvM0VZg0qK0+ee11mweEZyJGx+v148Z+IFiMEzTTACaOd+C7AnayDa7cEToeAZVxVzulWNbaiPmHZRVE+ly/nVgB9VYY1tVCwi6rQFyrmQjK/WVeT1uuGpLijtd4ss2smuR/zAETcVFmLVEeIIP/PyH35VN2teZ5qPeHvHy/wFAomrLHqUViMXy9/55y25jKkervv1c5W+tYO+U3shnH0DCRjMJ108nkSZKulefpKAwaypHze41aqj6iyWKZaQwd1zQ/gApobjqWP1MAp4PLMbogWEeoUfGlxx3oPZwebB9InLnkET29+sSpgJxEDD/90JFjZZkQbcflX3tzDPArcQmNbxvxFUaJzS5+B3rOQNJgtMVrFKHe/HrRE2dCBK5tKHXlfg+mfwpf1UKU0jfnqoeJHgMEPai4WidMn7cuPf+GLwqGcywctB2LzBbfoErA=
  - secure: byK+qL29tWtvPtPhjXsmtleRz8TLmlZMT001bxOrmx/o9r4MkBkALzLSCPYBJKeXOjTPKJ4zBJySrgMOtJ0VV0N/YjpJ7fMQpwCyK6EnqJFJbxBEKNVeK5x0X96E6Kq5CjRXFzKcnHK1hMsCJgjVDG9OXQC3E/EF+eTt5iL5hEXnnawDwbmTL5gjmjjKkeFIXeaoAoIb9PhU32auzEOPPzzmcT5PaVskFXzFy+cAR/P5GXiBgPB5ng1Dpkcijmu/+SWL2JLbiNK/UeS+jli+XaSCbQp1wY0DzScfqNkUrTf196atpTJNwznRBdcjd5wF44Lb+2CMOE57v/9rl536g77Nhsp1jX6AJt7uTLKjhgucj7URdyT7yVFt2BeYXKhf9WuhSaMrFbc83YQlQSbIo05UGf0NMTRlAivWCdRiJWK3qtrZvgHwAdOBP205e1dFRYYKaqcZzD5tZV8AIN6nveU2ug8lQ9CQve2Li7w+HE5c4qoWUzZpOz2+R/twRgt9yZO4ooCMis8z5OOqlZ4tghaC/wBoAoV0C2J79YMs7WSzY+t5De5/rBIhoxiVAvQSFxijgvBYHUtK6oydJNEv0h2QbtI+2x4Cr5AjuDw8Q678AIyqVbE07gkjtIZUtMC55367Xwt+wYWwKg4CWyZtlGp7gEAgKtGgFy5Ll7In9DA=
